#!/usr/bin/env python3

from arguments import parser
from time import sleep
from bluetooth import is_device_connected
from subprocess import run

if __name__ == "__main__":
    args = parser.parse_args()
    def should_execute_command(): return is_device_connected(args.mac_address) != args.unknot
    while True:
        if should_execute_command():
            run(args.command)
            while args.wait and should_execute_command():
                sleep(args.interval)

        sleep(args.interval)
